package skuber.operator.crd

import play.api.libs.json.*
import scala.deriving.Mirror

/**
 * Helper for creating Format instances for container types (List, Option, etc.)
 * when the element format is provided explicitly. This avoids implicit search
 * issues when the element type's format is generated by the same macro.
 */
object ContainerFormats:

  def listFormat[T](elementFormat: Format[T]): Format[List[T]] =
    Format(
      Reads.list(using elementFormat),
      Writes.list(using elementFormat)
    )

  def optionFormat[T](elementFormat: Format[T]): Format[Option[T]] =
    Format(
      Reads { json =>
        json.validateOpt(using elementFormat).map {
          case Some(null) => None
          case other => other
        }
      },
      Writes.optionWithNull(using elementFormat)
    )

  def setFormat[T](elementFormat: Format[T]): Format[Set[T]] =
    Format(
      Reads.set(using elementFormat),
      Writes.set(using elementFormat)
    )

  def seqFormat[T](elementFormat: Format[T]): Format[Seq[T]] =
    Format(
      Reads.seq(using elementFormat),
      Writes.seq(using elementFormat)
    )

  def mapFormat[V](valueFormat: Format[V]): Format[Map[String, V]] =
    Format(
      Reads.map(using valueFormat),
      Writes.map(using valueFormat)
    )

  def vectorFormat[T](elementFormat: Format[T]): Format[Vector[T]] =
    Format(
      Reads.seq(using elementFormat).map(_.toVector),
      Writes.seq(using elementFormat).contramap(_.toSeq)
    )

/**
 * Helper for creating OFormat instances for case classes with explicit field formats.
 * Used by @customResource macro to support nested case classes and container types.
 */
object CrdFormatHelper:

  /**
   * Create an OFormat for a case class, passing field formats explicitly.
   * This avoids compile-time implicit lookup which fails for macro-generated formats.
   *
   * @param fieldNames Names of the case class fields
   * @param fieldFormats Format instances for each field, in field order
   * @param mirror Mirror for the case class type
   */
  def createFormat[T](
    fieldNames: List[String],
    fieldFormats: List[Format[?]],
    mirror: Mirror.ProductOf[T]
  ): OFormat[T] = OFormat(
    Reads[T] { json =>
      try
        val values = fieldNames.zip(fieldFormats).map { (name, format) =>
          val value = (json \ name) match
            case JsDefined(v) => v
            case _: JsUndefined => JsNull
          value.as(using format.asInstanceOf[Reads[Any]])
        }
        val product = mirror.fromProduct(Tuple.fromArray(values.toArray))
        JsSuccess(product)
      catch
        case e: JsResultException => JsError(e.errors)
        case e: Exception => JsError(e.getMessage)
    },
    OWrites[T] { o =>
      val values = o.asInstanceOf[Product].productIterator.toList
      val pairs = fieldNames.zip(fieldFormats).zip(values).map { case ((name, format), value) =>
        name -> format.asInstanceOf[Writes[Any]].writes(value)
      }
      JsObject(pairs)
    }
  )
